name: 🚀 bot-service - deploy production

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bot-service

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Railway deploy to production
        run: railway up --service bot-service --env production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_BOT }}
