name: 🧪 bot-service - checks

on:
  pull_request:
    paths:
      - 'bot-service/**'

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bot-service

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test
