name: 🧪 check-main

on:
  push:
    branches: [main]

jobs:
  check-bot-service:
    uses: ./.github/workflows/_reusable-check.yml
    with:
      service: bot-service

  check-pricing-service:
    uses: ./.github/workflows/_reusable-check.yml
    with:
      service: pricing-service
