name: 🚀 i18n-service - deploy preview

on:
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: i18n-service

    steps:
      - uses: actions/checkout@v3

      - name: Railway deploy to testing
        run: railway up --service i18n-service --env testing
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_I18N }}
